import './globals.css'
import type { Metadata } from 'next'
import { Inter} from 'next/font/google'
import { Kdam_Thmor_Pro } from 'next/font/google';
import Navbar from './components/Navbar';
import Footer from './components/footer/Footer';

const kdam_Thmor_Pro = Kdam_Thmor_Pro({
  weight: '400', // Use the weights supported by the Kdam Thmor Pro font.
  style: 'normal', // Most likely 'normal' for Kdam Thmor Pro.
  display: 'swap', // 'swap', 'block', 'fallback', 'optional' are common values.
  subsets: ['khmer'], // If you need to support specific language subsets.
});



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Uniquely',
  description: 'Generated by Uniquely',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className={kdam_Thmor_Pro.className}>
        <div className=''>
           
           {children}
          
      </div>
      
        </body>
    </html>
  )
}
